name: Create Release Windows Only

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Windows Version
        run: |
          windres resource.rc -o resource.o
          g++ -O3 main-2.cpp resource.o -o Mandelbrot-2.exe -lgdi32 -luser32 -ldwmapi -fopenmp -static -mwindows
          strip Mandelbrot-2.exe
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Mandelbrot set. 32-bit. 60 FPS. 80-bit. OpenMP. Supersampling 2x2. Color rotation ${{ github.ref_name }}"
          body: |
            ## Mandelbrot set. 32-bit. 60 FPS. 80-bit. OpenMP. Supersampling 2x2. Color rotation 
            <video src="https://github.com/user-attachments/assets/44867c99-6c70-4fc0-a452-04e94b2598c9" controls width="600"></video>
            <video src="https://github.com/user-attachments/assets/532f09d5-8e03-4b66-b61d-017d38de88a1" controls width="600"></video>
            <video src="https://github.com/user-attachments/assets/79a4fa80-c936-4a9d-b1c2-3e9318bbb737" controls width="600"></video>
            - True 32-bit BGRA
            - Synchronization with DwmFlush
            - High-Precision Rendering (80-bit)
            - Multi-threaded performance (OpenMP)
            - True SSAA 2x2 (4 independent samples per pixel) direct RGB-space integration
            - Visual Aesthetics. Color rotation
          files: Mandelbrot-2.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PAT }}
