name: Create Release Windows Only

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Windows Version
        run: |
          g++ -O3 main-2.cpp -o Mandelbrot-2.exe -lgdi32 -luser32 -ldwmapi -fopenmp -static
          strip Mandelbrot-2.exe
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Mandelbrot Explorer WinAPI ${{ github.ref_name }}"
          body: |
            ## Windows Interactive Edition
            https://github.com/user-attachments/assets/572a4992-1cfc-4357-bbca-2c9d11733eaf
            - High-precision 80-bit rendering
            - WinAPI GUI with Real-time rotation
            - Multi-threaded performance (OpenMP)
          files: Mandelbrot-2.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PAT }}
